---
version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[nuget]: update"
    labels:
      - "dependencies"
      - "csharp"
      - "dotnet"
      - "nuget"
    assignees:
      - "iamtheantitwink"
    reviewers:
      - "iamtheantitwink"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[github-actions]: update"
    labels:
      - "dependencies"
      - "github-actions"
    assignees:
      - "iamtheantitwink"
    reviewers:
      - "iamtheantitwink"
